# H2
db.h2.url=jdbc:h2:./data/tarea2;DB_CLOSE_DELAY=-1
db.h2.user=sa
db.h2.password=

# MySQL
db.mysql.url=jdbc:mysql://localhost:3306/tarea2?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
db.mysql.user=user
db.mysql.password=user123

# Tipos
tipo.planta=maiz,arroz,yuca,frijol,mango
tipo.animal=vaca,chiva,curi,gallina,lombriz